# Лабораторная работа №7. "Полносвязные нейронные сети (многослойный персептрон). Решение задач регрессии и классификации"

*Задание №1.*
Решить задачи регрессии и классификации на данных в соответствии с Вашим индивидуальным вариантом (см. Лаб.работы №3, 4), используя полносвязные НС; реализовать НС посредством API Keras и фреймворка TensorFlow; оценить качество полученных моделей с помощью метрик.

*Задание №2.*
Разработать многослойный персептрон (MLP), с помощью которого можно решать задачи регрессии и классификации. Предусмотреть возможность использования таких функции активации, как sigmoid, tanh и relu; также предусмотреть возможность указать, сколько слоев нужно, сколько на каждом из них нейронов и какую функцию активации должен иметь слой. Реализовать обучение MLP методом обратного распространения ошибки; самостоятельно найти производные функций sigmoid, tanh и relu; реализовать классический градиентный спуск с возможностью указания шага.


*Дополнительное Задание №3*.*
1. Самостоятельно изучить отличия работы оптимизаторов Adam и RMSProp от классического градиентного спуска.
2. Реализовать градиентный спуск с использованием указанных оптимизаторов; предусмотрите возможность использования реализованных вами оптими-заторов в Вашем персептроне.

In [36]:
import pandas as pd
import numpy as np
from imblearn.under_sampling import NearMiss
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error
from sklearn.metrics import confusion_matrix, classification_report
import tensorflow as tf

## Задание №1

### Загрузка и разбиение датасетов на выборки 

In [37]:
data_regression = pd.read_csv("filteredNotes\Lab3.csv")
data_classification = pd.read_csv("filteredNotes\Lab4.csv")

In [38]:
y_regression = data_regression["price"]
X_regression = data_regression.drop(['price', 'Unnamed: 0'], axis=1)
y_classification = data_classification["bomb_planted"]
X_classification = data_classification.drop(['bomb_planted', 'Unnamed: 0'], axis=1)

In [39]:
data_regression

Unnamed: 0     price  bedrooms  bathrooms  sqft_living  floors  \
0               0  221900.0         3       1.00       1180.0       1   
1               1  538000.0         3       2.25       2570.0       2   
2               2  180000.0         2       1.00        770.0       1   
3               3  604000.0         4       3.00       1960.0       1   
4               4  510000.0         3       2.00       1680.0       1   
...           ...       ...       ...        ...          ...     ...   
21394       21608  360000.0         3       2.50       1530.0       3   
21395       21609  400000.0         4       2.50       2310.0       2   
21396       21610  402101.0         2       0.75       1020.0       2   
21397       21611  400000.0         3       2.50       1600.0       2   
21398       21612  325000.0         2       0.75       1020.0       2   

       waterfront  view  grade  sqft_above  sqft_basement  yr_built  \
0               0     0      7        1180              0      1955   
1               0     0      7        2170            400      1951   
2               0     0      6         770              0      1933   
3               0     0      7        1050            910      1965   
4               0     0      8        1680              0      1987   
...           ...   ...    ...         ...            ...       ...   
21394           0     0      8        1530              0      2009   
21395           0     0      8        2310              0      2014   
21396           0     0      7        1020              0      2009   
21397           0     0      8        1600              0      2004   
21398           0     0      7        1020              0      2008   

       yr_renovated  sqft_living15  sqft_lot15  
0                 0           1340        5650  
1              1991           1690        7639  
2                 0           2720        8062  
3                 0           1360        5000  
4                 0           1800        7503  
...             ...            ...         ...  
21394             0           1530        1509  
21395             0           1830        7200  
21396             0           1020        2007  
21397             0           1410        1287  
21398             0           1020        1357  

[21399 rows x 15 columns]

In [40]:
(
    X_regression_train,
    X_regression_test,
    y_regression_train,
    y_regression_test,
) = train_test_split(X_regression, y_regression, test_size=0.2)
(
    X_classification_train,
    X_classification_test,
    y_classification_train,
    y_classification_test,
) = train_test_split(
    X_classification, y_classification, stratify=y_classification, test_size=0.2
)

In [41]:
X_classification_train

time_left  ct_score  t_score  ct_health  t_health  ct_armor  t_armor  \
64793      54.94         1        1        372       100       478      100   
43877     169.95         9        5        500       500       292        0   
61543      74.89         1        5        500       467       499      435   
77802     114.95         2        0        500       500       493      500   
27626     166.88         7       10        500       500       500      450   
...          ...       ...      ...        ...       ...       ...      ...   
74778     174.85         8        8        500       500         0        0   
9155       46.89         6        3        500       400       498      353   
76500     105.06        14        8        500       500       471      500   
2747       37.87         8        5         89       199        81      200   
5476        5.48         6       12        147       300       174      300   

       ct_money  t_money  ct_helmets  t_helmets  ct_defuse_kits  \
64793      4950      300           5          1               3   
43877     19900    34700           0          0               2   
61543      8150    40100           1          5               3   
77802     10200      900           4          5               3   
27626      3650    15550           4          5               0   
...         ...      ...         ...        ...             ...   
74778     11100    18500           0          0               0   
9155        600    12800           4          4               2   
76500     26700     3650           5          5               5   
2747       1050     3700           1          2               1   
5476       3700     1350           2          3               1   

       ct_players_alive  t_players_alive  
64793                 5                1  
43877                 5                5  
61543                 5                5  
77802                 5                5  
27626                 5                5  
...                 ...              ...  
74778                 5                5  
9155                  5                4  
76500                 5                5  
2747                  1                2  
5476                  2                3  

[89590 rows x 14 columns]

### Обучение модели регрессии

In [42]:
# создаем модель, как набор последовательных слоев
model_regression = tf.keras.Sequential(
    [
        # Dense - полносвязный слой (каждый нейрон следующего слоя связан со всеми нейронами предыдущего)
        tf.keras.layers.Dense(64, activation="relu", input_shape=(13,)),
        # на втором скрытом слое будет 32 нейрона
        tf.keras.layers.Dense(32, activation="linear"),
        # Dropout позволяет внести фактор случайности - при обучении часть нейронов будет отключаться
        # каждый нейрон, в данном случае, будет отключаться с вероятностью 0.1
        tf.keras.layers.Dropout(0.1),
        tf.keras.layers.Dense(16, activation="relu"),
        tf.keras.layers.Dropout(0.1),
        # на выходе один нейрон, функция активации не применяется
        tf.keras.layers.Dense(1, activation="linear"),
    ]
)

In [43]:
model_regression.summary()

Model: "sequential_7"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_38 (Dense)            (None, 64)                896       
                                                                 
 dense_39 (Dense)            (None, 32)                2080      
                                                                 
 dropout_9 (Dropout)         (None, 32)                0         
                                                                 
 dense_40 (Dense)            (None, 16)                528       
                                                                 
 dropout_10 (Dropout)        (None, 16)                0         
                                                                 
 dense_41 (Dense)            (None, 1)                 17        
                                                                 
Total params: 3521 (13.75 KB)
Trainable params: 3521 (

In [44]:
model_regression.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="mse")

In [45]:
model_regression.fit(X_regression_train, y_regression_train, epochs=30)

Epoch 1/30


535/535 [==============================] - 2s 2ms/step - loss: 90627325952.0000
Epoch 2/30
535/535 [==============================] - 1s 2ms/step - loss: 63529549824.0000
Epoch 3/30
535/535 [==============================] - 1s 2ms/step - loss: 61284954112.0000
Epoch 4/30
535/535 [==============================] - 1s 2ms/step - loss: 59103240192.0000
Epoch 5/30
535/535 [==============================] - 1s 3ms/step - loss: 57780543488.0000
Epoch 6/30
535/535 [==============================] - 1s 2ms/step - loss: 54974423040.0000
Epoch 7/30
535/535 [==============================] - 1s 2ms/step - loss: 54865555456.0000
Epoch 8/30
535/535 [==============================] - 1s 2ms/step - loss: 53565091840.0000
Epoch 9/30
535/535 [==============================] - 1s 2ms/step - loss: 53061337088.0000
Epoch 10/30
535/535 [==============================] - 1s 2ms/step - loss: 53411323904.0000
Epoch 11/30
535/535 [==============================] - 1s 2ms/step - loss: 52380983296.0000
Epoch 12

In [46]:
print(mean_absolute_error(y_regression_test, model_regression.predict(X_regression_test)))
print(mean_squared_error(y_regression_test, model_regression.predict(X_regression_test)))

134/134 [==============================] - 0s 1ms/step
147937.88012740947
134/134 [==============================] - 0s 1ms/step
46843801690.93152


### Обучение модели классификации

In [47]:
model_classification_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(14,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # сначала используем 1 нейрон и sigmoid
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)
# в качестве функции активации используется бинарная  кроссэнтропия
model_classification_1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="mse")
# verbose=None - не будет логов
model_classification_1.fit(X_classification_train, y_classification_train, epochs=25, verbose=None)

In [48]:
model_classification_1.predict(X_classification_test, verbose=None)[:5]

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]], dtype=float32)

In [49]:
y_pred = np.around(model_classification_1.predict(X_classification_test, verbose=None))
print(classification_report(y_classification_test, y_pred))
print(confusion_matrix(y_classification_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     19752
           1       0.00      0.00      0.00      2646

    accuracy                           0.88     22398
   macro avg       0.44      0.50      0.47     22398
weighted avg       0.78      0.88      0.83     22398

[[19752     0]
 [ 2646     0]]


c:\Users\vlszg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vlszg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vlszg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

In [50]:
w0 = 1 / y_classification_train[y_classification_train==0].shape[0]
w1 = 1 / y_classification_train[y_classification_train==1].shape[0]

In [51]:
model_classification_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(14,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # используем 1 нейрон и sigmoid
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)
model_classification_1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="binary_crossentropy")
model_classification_1.fit(X_classification_train, y_classification_train, epochs=25, verbose=None,
                           class_weight={0: w0, 1: w1})
y_pred = np.around(model_classification_1.predict(X_classification_test, verbose=None))
print(classification_report(y_classification_test, y_pred))
print(confusion_matrix(y_classification_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      0.90      0.95     19752
           1       0.57      0.98      0.72      2646

    accuracy                           0.91     22398
   macro avg       0.78      0.94      0.83     22398
weighted avg       0.95      0.91      0.92     22398

[[17799  1953]
 [   44  2602]]


In [52]:
model_classification_2 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(14,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # сначала используем 2 нейрона и softmax
        tf.keras.layers.Dense(2, activation="softmax"),
    ]
)
# в качестве функции активации используется категориальная кроссэнтропия
# используем разряженный (sparse) вариант, поскольку значения целевого признака не закодированы One-Hot кодированием
model_classification_2.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.005), loss="sparse_categorical_crossentropy")
model_classification_2.fit(X_classification_train, y_classification_train, epochs=25, verbose=None,
                           class_weight={0: w0, 1: w1})

In [53]:
model_classification_2.predict(X_classification_test, verbose=None)[:5]

array([[0.48112917, 0.5188708 ],
       [0.48112917, 0.5188708 ],
       [0.48112917, 0.5188708 ],
       [0.48112917, 0.5188708 ],
       [0.48112917, 0.5188708 ]], dtype=float32)

In [54]:
y_pred = [np.argmax(pred) for pred in model_classification_2.predict(X_classification_test, verbose=None)]

In [55]:
print(classification_report(y_classification_test, y_pred))
print(confusion_matrix(y_classification_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00     19752
           1       0.12      1.00      0.21      2646

    accuracy                           0.12     22398
   macro avg       0.06      0.50      0.11     22398
weighted avg       0.01      0.12      0.02     22398

[[    0 19752]
 [    0  2646]]


c:\Users\vlszg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vlszg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vlszg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,

Попробуем устранить дисбаланс с помощью NearMiss

In [56]:
print(f'1: {sum(y_classification_train == 1)}')
print(f'0: {sum(y_classification_train == 0)}')

1: 10582
0: 79008


In [57]:
nm = NearMiss()
X_classification_train, y_classification_train = nm.fit_resample(X_classification_train, y_classification_train.ravel())

In [58]:
print(f'1: {sum(y_classification_train == 1)}')
print(f'0: {sum(y_classification_train == 0)}')

1: 10582
0: 10582


In [59]:
model_classification_1 = tf.keras.Sequential(
    [
        tf.keras.layers.Dense(64, activation="relu", input_shape=(14,)),
        tf.keras.layers.Dense(128, activation="relu"),
        tf.keras.layers.Dropout(0.05),
        tf.keras.layers.Dense(64, activation="relu"),
        tf.keras.layers.Dense(32, activation="relu"),
        tf.keras.layers.Dense(16, activation="relu"),
        # сначала используем 1 нейрон и sigmoid
        tf.keras.layers.Dense(1, activation="sigmoid"),
    ]
)
# в качестве функции активации используется бинарная  кроссэнтропия
model_classification_1.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.001), loss="mse")
# verbose=None - не будет логов
model_classification_1.fit(X_classification_train, y_classification_train, epochs=25, verbose=None)

In [61]:
y_pred = np.around(model_classification_1.predict(X_classification_test, verbose=None))
print(classification_report(y_classification_test, y_pred))
print(confusion_matrix(y_classification_test, y_pred))

              precision    recall  f1-score   support

           0       0.88      1.00      0.94     19752
           1       0.00      0.00      0.00      2646

    accuracy                           0.88     22398
   macro avg       0.44      0.50      0.47     22398
weighted avg       0.78      0.88      0.83     22398

[[19752     0]
 [ 2646     0]]


c:\Users\vlszg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vlszg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\vlszg\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\metrics\_classification.py:1471: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average,